name: Thiru_Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Build Creation"

  test:
     runs-on: ubuntu-latest
     steps:
       - name: Test Step
         run: echo "Testing Success"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deployment"
  

