name: Thirupathi Workflow
on: workflow_dispatch
jobs:
  Thirupathijob:
    runs-on: ubuntu-latest
    steps:
      - name: Thirupathi step
        run: |
          echo "Hello Thirupathi"
          echo "Hello Sriram and Siri"
  

