name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:

  action-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Application
        run: |
          echo "Building application..."
          mkdir build
          echo "Build completed"
          echo "Hello, ${{vars.MY_NAME}}"
          echo "I am from : ${{vars.MY_CITY}}"
          echo "My Password is: ${{secrets.PASSWORD}}"


